# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=rd_models.test_cube.animation.spin.playing] run function rd_models:test_cube/animations/spin/zzz/on_tick
execute on passengers run rotate @s ~ ~