# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function rd_models:blackstone_golem/animations/walk/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
function rd_models:blackstone_golem/animations/walk/zzz/zzz/1 with storage animated_java:temp entry.data.uuids_by_name
return 1