# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s CustomName set value ['',{text:rd_models.blackstone_golem,color:'#00aced'},'.',{text:block_display,color:light_purple},'.',{text:block_display7,color:gold}]
function animated_java:global/gu/get_entity_uuid_string
scoreboard players operation @s aj.id = aj.last_id aj.id