# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,-0.0602f,0f,-0.1329f,-0.0602f,1.4988f,0f,3.3073f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0301f,0f,0.6441f,-0.0301f,0.7494f,0f,2.6505f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0301f,0f,-0.1053f,-0.0301f,0.7494f,0f,2.6204f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0616f,-0.0426f,0f,0.9639f,-0.0426f,1.0616f,0f,2.4757f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0616f,-0.0426f,0f,-0.0978f,-0.0426f,1.0616f,0f,2.433f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.0125f,0f,0.6642f,-0.0301f,0.3122f,0f,2.1509f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.0125f,0f,-0.0852f,-0.0301f,0.3122f,0f,2.1208f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,-0.0251f,0f,-0.0601f,-0.0351f,0.6245f,0f,1.4963f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,-0.0251f,0f,0.8141f,-0.0351f,0.6245f,0f,1.5314f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8118f,-0.0296f,-0.0127f,1.7775f,-0.0326f,0.7358f,0.3167f,2.463f,0f,0.3434f,-0.6797f,0.1433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8118f,-0.0091f,-0.0127f,1.7866f,-0.0326f,0.2264f,0.3167f,2.2366f,0f,0.1057f,-0.6797f,0.0376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.025f,-0.0106f,2.0047f,-0.005f,0.6226f,0.2639f,1.4781f,0f,0.2906f,-0.5664f,-0.3888f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,-0.0386f,-0.0148f,1.8888f,-0.0351f,0.9622f,0.3695f,1.2505f,0f,0.449f,-0.793f,-0.3548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0159f,-0.0106f,1.7777f,-0.0251f,0.3962f,0.2639f,0.9021f,0f,0.1849f,-0.5664f,-0.653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0114f,-0.0042f,1.7277f,-0.01f,0.283f,0.1056f,0.5902f,0f,0.1321f,-0.2266f,-0.7284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0114f,-0.0042f,1.286f,-0.01f,0.283f,0.1056f,0.6859f,0f,0.1321f,-0.2266f,-0.6756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0136f,-0.0042f,1.8506f,-0.01f,0.3396f,0.1056f,0.6442f,0f,0.1585f,-0.2266f,-0.9814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0114f,-0.0042f,1.7192f,-0.01f,0.283f,0.1056f,0.8014f,0f,0.1321f,-0.2266f,-1.1815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,-0.0386f,0.0148f,-1.1268f,-0.0351f,0.9622f,-0.3695f,1.5788f,0f,-0.449f,-0.793f,1.1302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.025f,0.0106f,-2.0058f,-0.005f,0.6226f,-0.2639f,1.6607f,0f,-0.2906f,-0.5664f,0.9377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0114f,0.0042f,-1.103f,-0.01f,0.283f,-0.1056f,0.9864f,0f,-0.1321f,-0.2266f,1.3377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0114f,0.0042f,-1.5981f,-0.01f,0.283f,-0.1056f,0.8532f,0f,-0.1321f,-0.2266f,1.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0136f,0.0042f,-1.7165f,-0.01f,0.3396f,-0.1056f,0.686f,0f,-0.1585f,-0.2266f,1.1904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0114f,0.0042f,-1.5896f,-0.01f,0.283f,-0.1056f,0.642f,0f,-0.1321f,-0.2266f,0.9374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0159f,0.0106f,-1.2337f,-0.0251f,0.3962f,-0.2639f,1.1248f,0f,-0.1849f,-0.5664f,1.2018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8118f,-0.0091f,0.0127f,-1.1644f,-0.0326f,0.2264f,-0.3167f,2.5146f,0f,-0.1057f,-0.6797f,0.6246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8118f,-0.0296f,0.0127f,-1.1735f,-0.0326f,0.7358f,-0.3167f,2.741f,0f,-0.3434f,-0.6797f,0.5189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,-0.0546f,-0.0148f,-0.2467f,-0.0351f,1.3584f,0.3695f,-0.0891f,0f,0.6339f,-0.793f,-0.2169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,-0.0546f,0.0148f,1.11f,-0.0351f,1.3584f,-0.3695f,0.3942f,0f,-0.6339f,-0.793f,1.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000503503,"py":-0.002508237,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args