# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4989f,-0.0578f,0f,-0.1276f,-0.0578f,1.4989f,0f,3.3076f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0289f,0f,0.6484f,-0.0289f,0.7494f,0f,2.6495f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0289f,0f,-0.1011f,-0.0289f,0.7494f,0f,2.6206f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,-0.0409f,0f,0.9678f,-0.0409f,1.0617f,0f,2.4742f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,-0.0409f,0f,-0.0939f,-0.0409f,1.0617f,0f,2.4333f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.012f,0f,0.6676f,-0.0289f,0.3123f,0f,2.1499f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.012f,0f,-0.0818f,-0.0289f,0.3123f,0f,2.121f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,-0.0241f,0f,-0.0577f,-0.0337f,0.6245f,0f,1.4965f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,-0.0241f,0f,0.8166f,-0.0337f,0.6245f,0f,1.5302f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,-0.0284f,-0.0122f,1.7815f,-0.0313f,0.7364f,0.3156f,2.4607f,0f,0.3421f,-0.6803f,0.1443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,-0.0087f,-0.0122f,1.7902f,-0.0313f,0.2266f,0.3156f,2.2341f,0f,0.1053f,-0.6803f,0.039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.024f,-0.0101f,2.0071f,-0.0048f,0.6231f,0.263f,1.4746f,0f,0.2895f,-0.5669f,-0.3861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,-0.0371f,-0.0142f,1.8908f,-0.0337f,0.963f,0.3682f,1.2472f,0f,0.4474f,-0.7936f,-0.3517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0153f,-0.0101f,1.7792f,-0.0241f,0.3965f,0.263f,0.8985f,0f,0.1842f,-0.5669f,-0.6493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0109f,-0.0041f,1.7286f,-0.0096f,0.2832f,0.1052f,0.5865f,0f,0.1316f,-0.2268f,-0.7242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0109f,-0.0041f,1.2871f,-0.0096f,0.2832f,0.1052f,0.683f,0f,0.1316f,-0.2268f,-0.6715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0131f,-0.0041f,1.8517f,-0.0096f,0.3399f,0.1052f,0.6399f,0f,0.1579f,-0.2268f,-0.9772f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0109f,-0.0041f,1.7205f,-0.0096f,0.2832f,0.1052f,0.7969f,0f,0.1316f,-0.2268f,-1.1777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,-0.0371f,0.0142f,-1.1242f,-0.0337f,0.963f,-0.3682f,1.5787f,0f,-0.4474f,-0.7936f,1.1279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.024f,0.0101f,-2.0031f,-0.0048f,0.6231f,-0.263f,1.6623f,0f,-0.2895f,-0.5669f,0.9356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0109f,0.0041f,-1.1013f,-0.0096f,0.2832f,-0.1052f,0.9859f,0f,-0.1316f,-0.2268f,1.3344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0109f,0.0041f,-1.5966f,-0.0096f,0.2832f,-0.1052f,0.8534f,0f,-0.1316f,-0.2268f,1.387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0131f,0.0041f,-1.7153f,-0.0096f,0.3399f,-0.1052f,0.6867f,0f,-0.1579f,-0.2268f,1.1866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0109f,0.0041f,-1.5885f,-0.0096f,0.2832f,-0.1052f,0.643f,0f,-0.1316f,-0.2268f,0.9335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0153f,0.0101f,-1.2318f,-0.0241f,0.3965f,-0.263f,1.1248f,0f,-0.1842f,-0.5669f,1.1987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,-0.0087f,0.0122f,-1.1603f,-0.0313f,0.2266f,-0.3156f,2.5154f,0f,-0.1053f,-0.6803f,0.6238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,-0.0284f,0.0122f,-1.1691f,-0.0313f,0.7364f,-0.3156f,2.742f,0f,-0.3421f,-0.6803f,0.5185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,-0.0524f,-0.0142f,-0.2468f,-0.0337f,1.3595f,0.3682f,-0.0889f,0f,0.6316f,-0.7936f,-0.2143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,-0.0524f,0.0142f,1.1107f,-0.0337f,1.3595f,-0.3682f,0.3907f,0f,-0.6316f,-0.7936f,1.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000464033,"py":-0.0024079583,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args