# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,0.0602f,0f,0.133f,0.0602f,1.4988f,0f,3.3123f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,0.0301f,0f,0.8548f,0.0301f,0.7494f,0f,2.5953f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,0.0301f,0f,0.1054f,0.0301f,0.7494f,0f,2.6254f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0616f,0.0426f,0f,1.1595f,0.0426f,1.0616f,0f,2.3954f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0616f,0.0426f,0f,0.0979f,0.0426f,1.0616f,0f,2.438f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,0.0125f,0f,0.8347f,0.0301f,0.3122f,0f,2.0957f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,0.0125f,0f,0.0853f,0.0301f,0.3122f,0f,2.1258f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,0.0251f,0f,0.0602f,0.0351f,0.6245f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,0.0251f,0f,0.9345f,0.0351f,0.6245f,0f,1.4662f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8118f,0.0296f,-0.0127f,1.9865f,0.0326f,0.7358f,-0.3167f,2.7398f,0f,-0.3434f,-0.6797f,0.513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8118f,0.0091f,-0.0127f,1.9774f,0.0326f,0.2264f,-0.3167f,2.5134f,0f,-0.1057f,-0.6797f,0.6187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.025f,-0.0106f,2.1319f,0.005f,0.6226f,-0.2639f,1.6871f,0f,-0.2906f,-0.5664f,0.9319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,0.0386f,-0.0148f,2.0023f,0.0351f,0.9622f,-0.3695f,1.5751f,0f,-0.449f,-0.793f,1.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,0.0159f,-0.0106f,1.8593f,0.0251f,0.3962f,-0.2639f,1.1311f,0f,-0.1849f,-0.5664f,1.196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.0114f,-0.0042f,1.7866f,0.01f,0.283f,-0.1056f,0.8771f,0f,-0.1321f,-0.2266f,1.3847f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.0114f,-0.0042f,1.354f,0.01f,0.283f,-0.1056f,1.0078f,0f,-0.1321f,-0.2266f,1.3319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0136f,-0.0042f,1.905f,0.01f,0.3396f,-0.1056f,0.7099f,0f,-0.1585f,-0.2266f,1.1845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.0114f,-0.0042f,1.7781f,0.01f,0.283f,-0.1056f,0.6659f,0f,-0.1321f,-0.2266f,0.9315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,0.0386f,0.0148f,-1.0133f,0.0351f,0.9622f,0.3695f,1.2468f,0f,0.449f,-0.793f,-0.3489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.025f,0.0106f,-1.8787f,0.005f,0.6226f,0.2639f,1.5045f,0f,0.2906f,-0.5664f,-0.383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.0114f,0.0042f,-1.035f,0.01f,0.283f,0.1056f,0.7072f,0f,0.1321f,-0.2266f,-0.6697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.0114f,0.0042f,-1.5391f,0.01f,0.283f,0.1056f,0.6141f,0f,0.1321f,-0.2266f,-0.7225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0136f,0.0042f,-1.6621f,0.01f,0.3396f,0.1056f,0.6681f,0f,0.1585f,-0.2266f,-0.9755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.0114f,0.0042f,-1.5307f,0.01f,0.283f,0.1056f,0.8252f,0f,0.1321f,-0.2266f,-1.1757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,0.0159f,0.0106f,-1.152f,0.0251f,0.3962f,0.2639f,0.9084f,0f,0.1849f,-0.5664f,-0.6471f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8118f,0.0091f,0.0127f,-0.9736f,0.0326f,0.2264f,0.3167f,2.2354f,0f,0.1057f,-0.6797f,0.0435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8118f,0.0296f,0.0127f,-0.9645f,0.0326f,0.7358f,0.3167f,2.4618f,0f,0.3434f,-0.6797f,0.1491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,0.0546f,-0.0148f,-0.2359f,0.0351f,1.3584f,-0.3695f,0.3583f,0f,-0.6339f,-0.793f,0.9982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,0.0546f,0.0148f,1.1213f,0.0351f,1.3584f,0.3695f,-0.1134f,0f,0.6339f,-0.793f,-0.2433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000503503,"py":0.002508237,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args