# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,0.0595f,0f,0.1315f,0.0595f,1.4988f,0f,3.3124f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,0.0298f,0f,0.8536f,0.0298f,0.7494f,0f,2.5956f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,0.0298f,0f,0.1042f,0.0298f,0.7494f,0f,2.6254f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,0.0422f,0f,1.1585f,0.0422f,1.0617f,0f,2.3959f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,0.0422f,0f,0.0968f,0.0422f,1.0617f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,0.0124f,0f,0.8338f,0.0298f,0.3123f,0f,2.096f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,0.0124f,0f,0.0844f,0.0298f,0.3123f,0f,2.1258f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,0.0248f,0f,0.0596f,0.0347f,0.6245f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,0.0248f,0f,0.9339f,0.0347f,0.6245f,0f,1.4666f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,0.0293f,-0.0125f,1.9853f,0.0322f,0.7364f,-0.3156f,2.7396f,0f,-0.3421f,-0.6803f,0.5127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,0.009f,-0.0125f,1.9763f,0.0322f,0.2266f,-0.3156f,2.513f,0f,-0.1053f,-0.6803f,0.618f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.0248f,-0.0104f,2.1311f,0.005f,0.6231f,-0.263f,1.6862f,0f,-0.2895f,-0.5669f,0.9298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,0.0383f,-0.0146f,2.0015f,0.0347f,0.963f,-0.3681f,1.5738f,0f,-0.4474f,-0.7936f,1.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,0.0158f,-0.0104f,1.8588f,0.0248f,0.3965f,-0.263f,1.1297f,0f,-0.1842f,-0.5669f,1.1929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.0113f,-0.0042f,1.7861f,0.0099f,0.2832f,-0.1052f,0.8752f,0f,-0.1316f,-0.2268f,1.3812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.0113f,-0.0042f,1.3534f,0.0099f,0.2832f,-0.1052f,1.0059f,0f,-0.1316f,-0.2268f,1.3286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0135f,-0.0042f,1.9046f,0.0099f,0.3399f,-0.1052f,0.7085f,0f,-0.1579f,-0.2268f,1.1808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.0113f,-0.0042f,1.7777f,0.0099f,0.2832f,-0.1052f,0.6649f,0f,-0.1316f,-0.2268f,0.9277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,0.0383f,0.0146f,-1.0139f,0.0347f,0.9638f,0.3667f,1.2454f,0f,0.4457f,-0.7943f,-0.3427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.0248f,0.0104f,-1.8794f,0.005f,0.6236f,0.262f,1.5026f,0f,0.2884f,-0.5674f,-0.3775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.0113f,0.0042f,-1.0354f,0.0099f,0.2835f,0.1048f,0.7047f,0f,0.1311f,-0.2269f,-0.6615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.0113f,0.0042f,-1.5395f,0.0099f,0.2835f,0.1048f,0.6111f,0f,0.1311f,-0.2269f,-0.714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0135f,0.0042f,-1.6625f,0.0099f,0.3401f,0.1048f,0.6642f,0f,0.1573f,-0.2269f,-0.9671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.0113f,0.0042f,-1.5312f,0.0099f,0.2835f,0.1048f,0.8207f,0f,0.1311f,-0.2269f,-1.1679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,0.0158f,0.0104f,-1.1525f,0.0248f,0.3968f,0.262f,0.9059f,0f,0.1835f,-0.5674f,-0.6396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,0.009f,0.0125f,-0.9746f,0.0322f,0.2268f,0.3143f,2.2353f,0f,0.1049f,-0.6808f,0.0463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,0.0293f,0.0125f,-0.9656f,0.0322f,0.737f,0.3143f,2.4621f,0f,0.3408f,-0.6808f,0.1511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,0.054f,-0.0146f,-0.2361f,0.0347f,1.3595f,-0.3681f,0.3563f,0f,-0.6316f,-0.7936f,0.9963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,0.054f,0.0146f,1.1213f,0.0347f,1.3595f,0.3681f,-0.1132f,0f,0.6316f,-0.7936f,-0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000492514,"py":0.0024807263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args