# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.499f,0.0549f,0f,0.1213f,0.0549f,1.499f,0f,3.3126f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7495f,0.0275f,0f,0.8456f,0.0275f,0.7495f,0f,2.5981f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7495f,0.0275f,0f,0.0961f,0.0275f,0.7495f,0f,2.6255f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0618f,0.0389f,0f,1.1511f,0.0389f,1.0618f,0f,2.3993f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0618f,0.0389f,0f,0.0893f,0.0389f,1.0618f,0f,2.4382f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7495f,0.0114f,0f,0.8273f,0.0275f,0.3123f,0f,2.0984f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7495f,0.0114f,0f,0.0778f,0.0275f,0.3123f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,0.0229f,0f,0.055f,0.032f,0.6246f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,0.0229f,0f,0.9294f,0.032f,0.6246f,0f,1.4692f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,0.027f,-0.0114f,1.9767f,0.0297f,0.7382f,-0.3121f,2.7422f,0f,-0.3383f,-0.6819f,0.5118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,0.0083f,-0.0114f,1.9684f,0.0297f,0.2271f,-0.3121f,2.5151f,0f,-0.1041f,-0.6819f,0.6159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.0229f,-0.0095f,2.1257f,0.0046f,0.6246f,-0.2601f,1.6872f,0f,-0.2863f,-0.5682f,0.9234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,0.0354f,-0.0133f,1.9964f,0.032f,0.9653f,-0.3641f,1.5735f,0f,-0.4425f,-0.7955f,1.1152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,0.0146f,-0.0095f,1.855f,0.0229f,0.3975f,-0.2601f,1.1285f,0f,-0.1822f,-0.5682f,1.1837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.0104f,-0.0038f,1.7831f,0.0092f,0.2839f,-0.104f,0.8729f,0f,-0.1301f,-0.2273f,1.3707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.0104f,-0.0038f,1.3501f,0.0092f,0.2839f,-0.104f,1.0025f,0f,-0.1301f,-0.2273f,1.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0125f,-0.0038f,1.9021f,0.0092f,0.3407f,-0.104f,0.7075f,0f,-0.1562f,-0.2273f,1.1694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.0104f,-0.0038f,1.7755f,0.0092f,0.2839f,-0.104f,0.6648f,0f,-0.1301f,-0.2273f,0.9161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,0.0357f,0.0127f,-1.018f,0.032f,0.9745f,0.3473f,1.2357f,0f,0.422f,-0.803f,-0.2986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.0231f,0.0091f,-1.8843f,0.0046f,0.6305f,0.2481f,1.4893f,0f,0.273f,-0.5736f,-0.3389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.0105f,0.0036f,-1.0381f,0.0092f,0.2866f,0.0992f,0.6873f,0f,0.1241f,-0.2294f,-0.6042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.0105f,0.0036f,-1.5419f,0.0092f,0.2866f,0.0992f,0.591f,0f,0.1241f,-0.2294f,-0.6539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0126f,0.0036f,-1.6653f,0.0092f,0.3439f,0.0992f,0.6375f,0f,0.1489f,-0.2294f,-0.9081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.0105f,0.0036f,-1.5347f,0.0092f,0.2866f,0.0992f,0.7894f,0f,0.1241f,-0.2294f,-1.1127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,0.0147f,0.0091f,-1.1558f,0.0229f,0.4012f,0.2481f,0.8887f,0f,0.1738f,-0.5736f,-0.5871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,0.0084f,0.0109f,-0.9814f,0.0297f,0.2293f,0.2977f,2.235f,0f,0.0993f,-0.6883f,0.066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,0.0273f,0.0109f,-0.973f,0.0297f,0.7452f,0.2977f,2.4643f,0f,0.3227f,-0.6883f,0.1653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,0.0499f,-0.0133f,-0.2374f,0.032f,1.3628f,-0.3641f,0.35f,0f,-0.6246f,-0.7955f,0.9907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,0.0499f,0.0133f,1.1217f,0.032f,1.3628f,0.3641f,-0.1108f,0f,0.6246f,-0.7955f,-0.2326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000418987,"py":0.0022881383,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args