# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4994f,0.0424f,0f,0.0936f,0.0424f,1.4994f,0f,3.3129f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7497f,0.0212f,0f,0.8239f,0.0212f,0.7497f,0f,2.6045f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7497f,0.0212f,0f,0.0742f,0.0212f,0.7497f,0f,2.6257f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,0.03f,0f,1.1309f,0.03f,1.0621f,0f,2.4083f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,0.03f,0f,0.0689f,0.03f,1.0621f,0f,2.4383f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7497f,0.0088f,0f,0.8097f,0.0212f,0.3124f,0f,2.1047f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7497f,0.0088f,0f,0.06f,0.0212f,0.3124f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,0.0177f,0f,0.0424f,0.0247f,0.6248f,0f,1.5012f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,0.0177f,0f,0.917f,0.0247f,0.6248f,0f,1.4765f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,0.0211f,-0.0084f,1.9533f,0.0229f,0.7452f,-0.2982f,2.7452f,0f,-0.3232f,-0.6881f,0.5078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,0.0065f,-0.0084f,1.9468f,0.0229f,0.2293f,-0.2982f,2.5159f,0f,-0.0994f,-0.6881f,0.6072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0178f,-0.007f,2.1109f,0.0035f,0.6305f,-0.2485f,1.6832f,0f,-0.2735f,-0.5734f,0.8979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,0.0275f,-0.0098f,1.9825f,0.0247f,0.9744f,-0.3479f,1.5645f,0f,-0.4226f,-0.8028f,1.0872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,0.0113f,-0.007f,1.8448f,0.0177f,0.4012f,-0.2485f,1.1171f,0f,-0.174f,-0.5734f,1.1465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,0.0081f,-0.0028f,1.7749f,0.0071f,0.2866f,-0.0994f,0.8571f,0f,-0.1243f,-0.2294f,1.3281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,0.0081f,-0.0028f,1.3408f,0.0071f,0.2866f,-0.0994f,0.9841f,0f,-0.1243f,-0.2294f,1.2784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,0.0097f,-0.0028f,1.8954f,0.0071f,0.3439f,-0.0994f,0.6969f,0f,-0.1492f,-0.2294f,1.1236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,0.0081f,-0.0028f,1.7693f,0.0071f,0.2866f,-0.0994f,0.6583f,0f,-0.1243f,-0.2294f,0.8694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,0.0283f,0.0083f,-1.0286f,0.0247f,1.0005f,0.2934f,1.215f,0f,0.3564f,-0.8243f,-0.1785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0183f,0.0059f,-1.8971f,0.0035f,0.6474f,0.2096f,1.4582f,0f,0.2306f,-0.5888f,-0.2334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,0.0083f,0.0024f,-1.0447f,0.0071f,0.2943f,0.0838f,0.6474f,0f,0.1048f,-0.2355f,-0.447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,0.0083f,0.0024f,-1.5478f,0.0071f,0.2943f,0.0838f,0.5438f,0f,0.1048f,-0.2355f,-0.489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,0.01f,0.0024f,-1.672f,0.0071f,0.3531f,0.0838f,0.5723f,0f,0.1258f,-0.2355f,-0.7455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,0.0083f,0.0024f,-1.543f,0.0071f,0.2943f,0.0838f,0.7115f,0f,0.1048f,-0.2355f,-0.96f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,0.0116f,0.0059f,-1.164f,0.0177f,0.412f,0.2096f,0.8484f,0f,0.1468f,-0.5888f,-0.443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,0.0067f,0.0071f,-0.9998f,0.0229f,0.2354f,0.2515f,2.2365f,0f,0.0839f,-0.7065f,0.119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,0.0216f,0.0071f,-0.9931f,0.0229f,0.7651f,0.2515f,2.4719f,0f,0.2726f,-0.7065f,0.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,0.0389f,-0.0098f,-0.2409f,0.0247f,1.3757f,-0.3479f,0.3262f,0f,-0.5966f,-0.8028f,0.968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,0.0389f,0.0098f,1.1225f,0.0247f,1.3757f,0.3479f,-0.1051f,0f,0.5966f,-0.8028f,-0.2004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000249351,"py":0.001765295,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args