# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4999f,0.0179f,0f,0.0396f,0.0179f,1.4999f,0f,3.313f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7499f,0.009f,0f,0.7813f,0.009f,0.7499f,0f,2.6166f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7499f,0.009f,0f,0.0314f,0.009f,0.7499f,0f,2.6256f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0624f,0.0127f,0f,1.0916f,0.0127f,1.0624f,0f,2.4254f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0624f,0.0127f,0f,0.0291f,0.0127f,1.0624f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7499f,0.0037f,0f,0.7753f,0.009f,0.3125f,0f,2.1166f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7499f,0.0037f,0f,0.0254f,0.009f,0.3125f,0f,2.1256f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8749f,0.0075f,0f,0.0179f,0.0105f,0.625f,0f,1.5006f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8749f,0.0075f,0f,0.8929f,0.0105f,0.625f,0f,1.4902f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8124f,0.0092f,-0.0029f,1.9077f,0.0097f,0.7693f,-0.2411f,2.7246f,0f,-0.2612f,-0.7102f,0.4891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8124f,0.0028f,-0.0029f,1.9049f,0.0097f,0.2367f,-0.2411f,2.4879f,0f,-0.0804f,-0.7102f,0.5695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0078f,-0.0024f,2.0822f,0.0015f,0.651f,-0.2009f,1.637f,0f,-0.221f,-0.5918f,0.7915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8749f,0.012f,-0.0034f,1.9556f,0.0105f,1.006f,-0.2812f,1.5012f,0f,-0.3415f,-0.8286f,0.9702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.625f,0.005f,-0.0024f,1.8252f,0.0075f,0.4143f,-0.2009f,1.0482f,0f,-0.1406f,-0.5918f,0.9924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,0.0035f,-0.001f,1.7594f,0.003f,0.2959f,-0.0804f,0.7732f,0f,-0.1004f,-0.2367f,1.1521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,0.0035f,-0.001f,1.3233f,0.003f,0.2959f,-0.0804f,0.8968f,0f,-0.1004f,-0.2367f,1.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,0.0042f,-0.001f,1.8827f,0.003f,0.3551f,-0.0804f,0.6321f,0f,-0.1205f,-0.2367f,0.9354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,0.0035f,-0.001f,1.7574f,0.003f,0.2959f,-0.0804f,0.6125f,0f,-0.1004f,-0.2367f,0.6786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8749f,0.0124f,0.0022f,-1.0483f,0.0105f,1.0384f,0.1849f,1.1972f,0f,0.2245f,-0.8552f,0.0564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.008f,0.0016f,-1.9207f,0.0015f,0.6719f,0.1321f,1.4173f,0f,0.1453f,-0.6109f,-0.0262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,0.0036f,0.0006f,-1.0554f,0.003f,0.3054f,0.0528f,0.5996f,0f,0.066f,-0.2444f,-0.1368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,0.0036f,0.0006f,-1.5568f,0.003f,0.3054f,0.0528f,0.4834f,0f,0.066f,-0.2444f,-0.1632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,0.0044f,0.0006f,-1.6819f,0.003f,0.3665f,0.0528f,0.4766f,0f,0.0792f,-0.2444f,-0.4208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,0.0036f,0.0006f,-1.5556f,0.003f,0.3054f,0.0528f,0.589f,0f,0.066f,-0.2444f,-0.6519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.625f,0.0051f,0.0016f,-1.1781f,0.0075f,0.4276f,0.1321f,0.7975f,0f,0.0925f,-0.6109f,-0.1582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8124f,0.0029f,0.0019f,-1.0357f,0.0097f,0.2443f,0.1585f,2.2489f,0f,0.0528f,-0.7331f,0.2198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8124f,0.0095f,0.0019f,-1.0328f,0.0097f,0.7941f,0.1585f,2.4932f,0f,0.1717f,-0.7331f,0.2727f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8749f,0.017f,-0.0034f,-0.2471f,0.0105f,1.4203f,-0.2812f,0.2407f,0f,-0.4822f,-0.8286f,0.873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8749f,0.017f,0.0034f,1.124f,0.0105f,1.4203f,0.2812f,-0.0938f,0f,0.4822f,-0.8286f,-0.0712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000044619,"py":0.0007468048,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args