# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4994f,-0.0424f,0f,-0.0935f,-0.0424f,1.4994f,0f,3.3094f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7497f,-0.0212f,0f,0.6756f,-0.0212f,0.7497f,0f,2.6434f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7497f,-0.0212f,0f,-0.0741f,-0.0212f,0.7497f,0f,2.6222f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,-0.03f,0f,0.9933f,-0.03f,1.0621f,0f,2.4648f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,-0.03f,0f,-0.0688f,-0.03f,1.0621f,0f,2.4348f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7497f,-0.0088f,0f,0.6897f,-0.0212f,0.3124f,0f,2.1436f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7497f,-0.0088f,0f,-0.06f,-0.0212f,0.3124f,0f,2.1224f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,-0.0177f,0f,-0.0423f,-0.0247f,0.6248f,0f,1.4976f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,-0.0177f,0f,0.8323f,-0.0247f,0.6248f,0f,1.5224f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,-0.0217f,-0.0068f,1.8058f,-0.0229f,0.7691f,0.241f,2.4752f,0f,0.2612f,-0.7102f,0.2078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,-0.0067f,-0.0068f,1.8125f,-0.0229f,0.2366f,0.241f,2.2386f,0f,0.0804f,-0.7102f,0.1275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,-0.0184f,-0.0057f,2.0227f,-0.0035f,0.6508f,0.2008f,1.4357f,0f,0.221f,-0.5918f,-0.213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,-0.0284f,-0.0079f,1.9039f,-0.0247f,1.0057f,0.2811f,1.2146f,0f,0.3415f,-0.8286f,-0.1549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,-0.0117f,-0.0057f,1.7895f,-0.0177f,0.4141f,0.2008f,0.8371f,0f,0.1406f,-0.5918f,-0.4139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,-0.0084f,-0.0023f,1.736f,-0.0071f,0.2958f,0.0803f,0.5194f,0f,0.1004f,-0.2367f,-0.4551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,-0.0084f,-0.0023f,1.2953f,-0.0071f,0.2958f,0.0803f,0.6254f,0f,0.1004f,-0.2367f,-0.415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,-0.01f,-0.0023f,1.8603f,-0.0071f,0.355f,0.0803f,0.5441f,0f,0.1205f,-0.2367f,-0.712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,-0.0084f,-0.0023f,1.7315f,-0.0071f,0.2958f,0.0803f,0.6801f,0f,0.1004f,-0.2367f,-0.9286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,-0.0293f,0.0052f,-1.1015f,-0.0247f,1.0381f,-0.1848f,1.3629f,0f,-0.2245f,-0.8552f,0.796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,-0.019f,0.0037f,-1.9805f,-0.0035f,0.6717f,-0.132f,1.4949f,0f,-0.1453f,-0.6109f,0.6342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,-0.0086f,0.0015f,-1.0838f,-0.0071f,0.3053f,-0.0528f,0.739f,0f,-0.066f,-0.2444f,0.867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,-0.0086f,0.0015f,-1.5802f,-0.0071f,0.3053f,-0.0528f,0.6028f,0f,-0.066f,-0.2444f,0.8934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,-0.0104f,0.0015f,-1.7019f,-0.0071f,0.3664f,-0.0528f,0.4854f,0f,-0.0792f,-0.2444f,0.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,-0.0086f,0.0015f,-1.5772f,-0.0071f,0.3053f,-0.0528f,0.4971f,0f,-0.066f,-0.2444f,0.4047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,-0.0121f,0.0037f,-1.2136f,-0.0177f,0.4274f,-0.132f,0.9055f,0f,-0.0925f,-0.6109f,0.7663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,-0.0069f,0.0045f,-1.1304f,-0.0229f,0.2443f,-0.1584f,2.3877f,0f,-0.0528f,-0.7331f,0.5104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,-0.0224f,0.0045f,-1.1373f,-0.0229f,0.7938f,-0.1584f,2.632f,0f,-0.1717f,-0.7331f,0.4576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,-0.0401f,-0.0079f,-0.2475f,-0.0247f,1.4198f,0.2811f,-0.0932f,0f,0.4822f,-0.8286f,-0.0511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,-0.0401f,0.0079f,1.1178f,-0.0247f,1.4198f,-0.2811f,0.2702f,0f,-0.4822f,-0.8286f,0.8931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000249351,"py":-0.001765295,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args