# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.499f,-0.0549f,0f,-0.1212f,-0.0549f,1.499f,0f,3.308f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7495f,-0.0275f,0f,0.6534f,-0.0275f,0.7495f,0f,2.6484f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7495f,-0.0275f,0f,-0.0961f,-0.0275f,0.7495f,0f,2.621f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0618f,-0.0389f,0f,0.9726f,-0.0389f,1.0618f,0f,2.4725f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0618f,-0.0389f,0f,-0.0892f,-0.0389f,1.0618f,0f,2.4336f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7495f,-0.0114f,0f,0.6717f,-0.0275f,0.3123f,0f,2.1487f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7495f,-0.0114f,0f,-0.0778f,-0.0275f,0.3123f,0f,2.1213f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,-0.0229f,0f,-0.0549f,-0.032f,0.6246f,0f,1.4967f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,-0.0229f,0f,0.8195f,-0.032f,0.6246f,0f,1.5287f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,-0.0273f,-0.0109f,1.7859f,-0.0297f,0.745f,0.2981f,2.4645f,0f,0.3232f,-0.6881f,0.1597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,-0.0084f,-0.0109f,1.7943f,-0.0297f,0.2292f,0.2981f,2.2352f,0f,0.0994f,-0.6881f,0.0603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0231f,-0.0091f,2.0102f,-0.0046f,0.6304f,0.2484f,1.4647f,0f,0.2735f,-0.5734f,-0.3451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,-0.0357f,-0.0127f,1.8934f,-0.032f,0.9742f,0.3478f,1.2385f,0f,0.4226f,-0.8028f,-0.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,-0.0147f,-0.0091f,1.7813f,-0.0229f,0.4011f,0.2484f,0.8825f,0f,0.174f,-0.5734f,-0.5937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0105f,-0.0036f,1.7303f,-0.0092f,0.2865f,0.0994f,0.5688f,0f,0.1243f,-0.2294f,-0.6606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0105f,-0.0036f,1.2889f,-0.0092f,0.2865f,0.0994f,0.6674f,0f,0.1243f,-0.2294f,-0.6109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0126f,-0.0036f,1.8537f,-0.0092f,0.3438f,0.0994f,0.6155f,0f,0.1492f,-0.2294f,-0.9149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0105f,-0.0036f,1.723f,-0.0092f,0.2865f,0.0994f,0.7676f,0f,0.1243f,-0.2294f,-1.1194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,-0.0366f,0.0107f,-1.1174f,-0.032f,1.0003f,-0.2933f,1.4769f,0f,-0.3564f,-0.8243f,0.9956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.0237f,0.0077f,-1.9967f,-0.0046f,0.6472f,-0.2095f,1.5795f,0f,-0.2306f,-0.5888f,0.8149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0108f,0.0031f,-1.095f,-0.0092f,0.2942f,-0.0838f,0.8676f,0f,-0.1048f,-0.2355f,1.1463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0108f,0.0031f,-1.5904f,-0.0092f,0.2942f,-0.0838f,0.7316f,0f,-0.1048f,-0.2355f,1.1883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0129f,0.0031f,-1.7101f,-0.0092f,0.353f,-0.0838f,0.5844f,0f,-0.1258f,-0.2355f,0.9737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0108f,0.0031f,-1.5843f,-0.0092f,0.2942f,-0.0838f,0.564f,0f,-0.1048f,-0.2355f,0.7173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,-0.0151f,0.0077f,-1.2257f,-0.0229f,0.4119f,-0.2095f,1.0186f,0f,-0.1468f,-0.5888f,1.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,-0.0086f,0.0092f,-1.1532f,-0.0297f,0.2354f,-0.2514f,2.4562f,0f,-0.0839f,-0.7065f,0.5803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,-0.028f,0.0092f,-1.1619f,-0.0297f,0.7649f,-0.2514f,2.6916f,0f,-0.2726f,-0.7065f,0.4964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,-0.0504f,-0.0127f,-0.2469f,-0.032f,1.3753f,0.3478f,-0.0917f,0f,0.5966f,-0.8028f,-0.1755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,-0.0504f,0.0127f,1.1125f,-0.032f,1.3753f,-0.3478f,0.3613f,0f,-0.5966f,-0.8028f,0.9929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000418987,"py":-0.0022881383,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args