# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,-0.0595f,0f,-0.1314f,-0.0595f,1.4988f,0f,3.3074f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0298f,0f,0.6453f,-0.0298f,0.7494f,0f,2.6502f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0298f,0f,-0.1041f,-0.0298f,0.7494f,0f,2.6205f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,-0.0422f,0f,0.965f,-0.0422f,1.0617f,0f,2.4753f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,-0.0422f,0f,-0.0967f,-0.0422f,1.0617f,0f,2.4331f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.0124f,0f,0.6651f,-0.0298f,0.3123f,0f,2.1506f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.0124f,0f,-0.0843f,-0.0298f,0.3123f,0f,2.1208f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,-0.0248f,0f,-0.0595f,-0.0347f,0.6245f,0f,1.4963f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,-0.0248f,0f,0.8148f,-0.0347f,0.6245f,0f,1.5311f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,-0.0293f,-0.0124f,1.7785f,-0.0322f,0.7381f,0.3121f,2.4641f,0f,0.3383f,-0.6819f,0.1474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,-0.009f,-0.0124f,1.7876f,-0.0322f,0.2271f,0.3121f,2.237f,0f,0.1041f,-0.6819f,0.0433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0248f,-0.0103f,2.0055f,-0.005f,0.6246f,0.2601f,1.4755f,0f,0.2863f,-0.5682f,-0.3779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,-0.0383f,-0.0145f,1.8894f,-0.0347f,0.9652f,0.3641f,1.2482f,0f,0.4425f,-0.7955f,-0.3423f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0158f,-0.0103f,1.7782f,-0.0248f,0.3974f,0.2601f,0.8978f,0f,0.1822f,-0.5682f,-0.6382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0113f,-0.0041f,1.7281f,-0.0099f,0.2839f,0.104f,0.5854f,0f,0.1301f,-0.2273f,-0.7115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0113f,-0.0041f,1.2864f,-0.0099f,0.2839f,0.104f,0.6816f,0f,0.1301f,-0.2273f,-0.6594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0135f,-0.0041f,1.8511f,-0.0099f,0.3407f,0.104f,0.6376f,0f,0.1562f,-0.2273f,-0.9648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0113f,-0.0041f,1.7198f,-0.0099f,0.2839f,0.104f,0.7935f,0f,0.1301f,-0.2273f,-1.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,-0.0387f,0.0138f,-1.1248f,-0.0347f,0.9743f,-0.3472f,1.5466f,0f,-0.422f,-0.803f,1.0914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.025f,0.0099f,-2.004f,-0.005f,0.6305f,-0.248f,1.6342f,0f,-0.273f,-0.5736f,0.9022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0114f,0.0039f,-1.1011f,-0.0099f,0.2866f,-0.0992f,0.9486f,0f,-0.1241f,-0.2294f,1.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0114f,0.0039f,-1.5961f,-0.0099f,0.2866f,-0.0992f,0.8142f,0f,-0.1241f,-0.2294f,1.3319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0137f,0.0039f,-1.7148f,-0.0099f,0.3439f,-0.0992f,0.6527f,0f,-0.1489f,-0.2294f,1.1273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0114f,0.0039f,-1.5882f,-0.0099f,0.2866f,-0.0992f,0.6158f,0f,-0.1241f,-0.2294f,0.873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0159f,0.0099f,-1.2318f,-0.0248f,0.4012f,-0.248f,1.0908f,0f,-0.1738f,-0.5736f,1.1504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,-0.0091f,0.0118f,-1.1625f,-0.0322f,0.2293f,-0.2976f,2.4961f,0f,-0.0993f,-0.6883f,0.6121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,-0.0296f,0.0118f,-1.1716f,-0.0322f,0.7451f,-0.2976f,2.7254f,0f,-0.3227f,-0.6883f,0.5128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,-0.0541f,-0.0145f,-0.2467f,-0.0347f,1.3627f,0.3641f,-0.09f,0f,0.6246f,-0.7955f,-0.2065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,-0.0541f,0.0145f,1.1105f,-0.0347f,1.3627f,-0.3641f,0.3864f,0f,-0.6246f,-0.7955f,1.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000492514,"py":-0.0024807263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args