# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,-0.0602f,0f,-0.1329f,-0.0602f,1.4988f,0f,3.3073f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0301f,0f,0.6441f,-0.0301f,0.7494f,0f,2.6505f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0301f,0f,-0.1053f,-0.0301f,0.7494f,0f,2.6204f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0616f,-0.0426f,0f,0.9639f,-0.0426f,1.0616f,0f,2.4757f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0616f,-0.0426f,0f,-0.0978f,-0.0426f,1.0616f,0f,2.433f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.0125f,0f,0.6642f,-0.0301f,0.3122f,0f,2.1509f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.0125f,0f,-0.0852f,-0.0301f,0.3122f,0f,2.1208f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,-0.0251f,0f,-0.0601f,-0.0351f,0.6245f,0f,1.4963f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,-0.0251f,0f,0.8141f,-0.0351f,0.6245f,0f,1.5314f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8118f,-0.0296f,-0.0127f,1.7775f,-0.0326f,0.7364f,0.3156f,2.4635f,0f,0.3421f,-0.6803f,0.1443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8118f,-0.0091f,-0.0127f,1.7866f,-0.0326f,0.2266f,0.3156f,2.2369f,0f,0.1053f,-0.6803f,0.039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.025f,-0.0106f,2.0048f,-0.005f,0.6231f,0.263f,1.4777f,0f,0.2895f,-0.5669f,-0.3861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,-0.0387f,-0.0148f,1.8888f,-0.0351f,0.9629f,0.3681f,1.2501f,0f,0.4474f,-0.7936f,-0.3517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0159f,-0.0106f,1.7777f,-0.0251f,0.3965f,0.263f,0.9012f,0f,0.1842f,-0.5669f,-0.6493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0114f,-0.0042f,1.7277f,-0.01f,0.2832f,0.1052f,0.5892f,0f,0.1316f,-0.2268f,-0.7242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0114f,-0.0042f,1.286f,-0.01f,0.2832f,0.1052f,0.6849f,0f,0.1316f,-0.2268f,-0.6715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0137f,-0.0042f,1.8506f,-0.01f,0.3399f,0.1052f,0.6428f,0f,0.1579f,-0.2268f,-0.9772f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0114f,-0.0042f,1.7192f,-0.01f,0.2832f,0.1052f,0.7996f,0f,0.1316f,-0.2268f,-1.1777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,-0.0387f,0.0147f,-1.1267f,-0.0351f,0.9637f,-0.3667f,1.5747f,0f,-0.4457f,-0.7943f,1.1254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.025f,0.0105f,-2.0057f,-0.005f,0.6236f,-0.2619f,1.6572f,0f,-0.2884f,-0.5674f,0.9333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0114f,0.0042f,-1.1028f,-0.01f,0.2835f,-0.1048f,0.9816f,0f,-0.1311f,-0.2269f,1.3309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0114f,0.0042f,-1.5979f,-0.01f,0.2835f,-0.1048f,0.8481f,0f,-0.1311f,-0.2269f,1.3833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0137f,0.0042f,-1.7163f,-0.01f,0.3401f,-0.1048f,0.6816f,0f,-0.1573f,-0.2269f,1.1826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0114f,0.0042f,-1.5895f,-0.01f,0.2835f,-0.1048f,0.6386f,0f,-0.1311f,-0.2269f,0.9294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0159f,0.0105f,-1.2335f,-0.0251f,0.3968f,-0.2619f,1.1204f,0f,-0.1835f,-0.5674f,1.1955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8118f,-0.0091f,0.0126f,-1.1643f,-0.0326f,0.2268f,-0.3143f,2.5122f,0f,-0.1049f,-0.6808f,0.623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8118f,-0.0296f,0.0126f,-1.1734f,-0.0326f,0.737f,-0.3143f,2.739f,0f,-0.3408f,-0.6808f,0.5182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,-0.0546f,-0.0148f,-0.2467f,-0.0351f,1.3594f,0.3681f,-0.0894f,0f,0.6316f,-0.7936f,-0.2143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,-0.0546f,0.0148f,1.1101f,-0.0351f,1.3594f,-0.3681f,0.3924f,0f,-0.6316f,-0.7936f,1.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000503503,"py":-0.002508237,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args