# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4991f,-0.0506f,0f,-0.1116f,-0.0506f,1.4991f,0f,3.3085f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7496f,-0.0253f,0f,0.6611f,-0.0253f,0.7496f,0f,2.6467f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7496f,-0.0253f,0f,-0.0885f,-0.0253f,0.7496f,0f,2.6214f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0619f,-0.0358f,0f,0.9798f,-0.0358f,1.0619f,0f,2.4698f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0619f,-0.0358f,0f,-0.0821f,-0.0358f,1.0619f,0f,2.434f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7496f,-0.0105f,0f,0.678f,-0.0253f,0.3123f,0f,2.147f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7496f,-0.0105f,0f,-0.0716f,-0.0253f,0.3123f,0f,2.1217f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8745f,-0.0211f,0f,-0.0505f,-0.0295f,0.6246f,0f,1.497f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8745f,-0.0211f,0f,0.824f,-0.0295f,0.6246f,0f,1.5265f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,-0.0249f,-0.0105f,1.7933f,-0.0274f,0.7383f,0.3121f,2.4538f,0f,0.3383f,-0.6819f,0.1474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,-0.0077f,-0.0105f,1.8009f,-0.0274f,0.2272f,0.3121f,2.2266f,0f,0.1041f,-0.6819f,0.0433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0211f,-0.0088f,2.0143f,-0.0042f,0.6247f,0.2601f,1.4639f,0f,0.2863f,-0.5682f,-0.3779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8745f,-0.0326f,-0.0123f,1.8968f,-0.0295f,0.9654f,0.3642f,1.2373f,0f,0.4425f,-0.7955f,-0.3423f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,-0.0134f,-0.0088f,1.7836f,-0.0211f,0.3975f,0.2601f,0.8875f,0f,0.1822f,-0.5682f,-0.6382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,-0.0096f,-0.0035f,1.7315f,-0.0084f,0.284f,0.104f,0.5755f,0f,0.1301f,-0.2273f,-0.7115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,-0.0096f,-0.0035f,1.2905f,-0.0084f,0.284f,0.104f,0.6743f,0f,0.1301f,-0.2273f,-0.6594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,-0.0115f,-0.0035f,1.8549f,-0.0084f,0.3407f,0.104f,0.6269f,0f,0.1562f,-0.2273f,-0.9648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,-0.0096f,-0.0035f,1.7245f,-0.0084f,0.284f,0.104f,0.7836f,0f,0.1301f,-0.2273f,-1.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8745f,-0.0326f,0.0123f,-1.1164f,-0.0295f,0.9654f,-0.3642f,1.5783f,0f,-0.4425f,-0.7955f,1.1208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.0211f,0.0088f,-1.9949f,-0.0042f,0.6247f,-0.2601f,1.6672f,0f,-0.2863f,-0.5682f,0.9291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,-0.0096f,0.0035f,-1.0963f,-0.0084f,0.284f,-0.104f,0.9844f,0f,-0.1301f,-0.2273f,1.3243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,-0.0096f,0.0035f,-1.5922f,-0.0084f,0.284f,-0.104f,0.854f,0f,-0.1301f,-0.2273f,1.3763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,-0.0115f,0.0035f,-1.7117f,-0.0084f,0.3407f,-0.104f,0.6889f,0f,-0.1562f,-0.2273f,1.1751f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,-0.0096f,0.0035f,-1.5852f,-0.0084f,0.284f,-0.104f,0.6459f,0f,-0.1301f,-0.2273f,0.9218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,-0.0134f,0.0088f,-1.2261f,-0.0211f,0.3975f,-0.2601f,1.1246f,0f,-0.1822f,-0.5682f,1.1894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,-0.0077f,0.0105f,-1.1481f,-0.0274f,0.2272f,-0.3121f,2.5178f,0f,-0.1041f,-0.6819f,0.6216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,-0.0249f,0.0105f,-1.1557f,-0.0274f,0.7383f,-0.3121f,2.7449f,0f,-0.3383f,-0.6819f,0.5174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8745f,-0.046f,-0.0123f,-0.2472f,-0.0295f,1.363f,0.3642f,-0.0881f,0f,0.6246f,-0.7955f,-0.2065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8745f,-0.046f,0.0123f,1.1128f,-0.0295f,1.363f,-0.3642f,0.3801f,0f,-0.6246f,-0.7955f,1.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000355286,"py":-0.0021070857,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args