# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4995f,-0.0385f,0f,-0.0851f,-0.0385f,1.4995f,0f,3.3098f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7498f,-0.0193f,0f,0.6823f,-0.0193f,0.7498f,0f,2.6418f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7498f,-0.0193f,0f,-0.0674f,-0.0193f,0.7498f,0f,2.6225f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,-0.0273f,0f,0.9996f,-0.0273f,1.0621f,0f,2.4624f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,-0.0273f,0f,-0.0626f,-0.0273f,1.0621f,0f,2.4351f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7498f,-0.008f,0f,0.6952f,-0.0193f,0.3124f,0f,2.142f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7498f,-0.008f,0f,-0.0546f,-0.0193f,0.3124f,0f,2.1227f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,-0.0161f,0f,-0.0385f,-0.0225f,0.6248f,0f,1.4979f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,-0.0161f,0f,0.8362f,-0.0225f,0.6248f,0f,1.5204f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,-0.0191f,-0.0077f,1.8128f,-0.0209f,0.7452f,0.2982f,2.4455f,0f,0.3232f,-0.6881f,0.1597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,-0.0059f,-0.0077f,1.8186f,-0.0209f,0.2293f,0.2982f,2.2162f,0f,0.0994f,-0.6881f,0.0603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,-0.0162f,-0.0064f,2.0261f,-0.0032f,0.6306f,0.2485f,1.4433f,0f,0.2735f,-0.5734f,-0.3451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,-0.025f,-0.0089f,1.9068f,-0.0225f,0.9745f,0.3479f,1.2184f,0f,0.4226f,-0.8028f,-0.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,-0.0103f,-0.0064f,1.7909f,-0.0161f,0.4013f,0.2485f,0.8637f,0f,0.174f,-0.5734f,-0.5937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,-0.0074f,-0.0026f,1.7364f,-0.0064f,0.2866f,0.0994f,0.5506f,0f,0.1243f,-0.2294f,-0.6606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,-0.0074f,-0.0026f,1.2961f,-0.0064f,0.2866f,0.0994f,0.654f,0f,0.1243f,-0.2294f,-0.6109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,-0.0088f,-0.0026f,1.8603f,-0.0064f,0.3439f,0.0994f,0.5959f,0f,0.1492f,-0.2294f,-0.9149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,-0.0074f,-0.0026f,1.7313f,-0.0064f,0.2866f,0.0994f,0.7494f,0f,0.1243f,-0.2294f,-1.1194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,-0.025f,0.0089f,-1.1031f,-0.0225f,0.9745f,-0.3479f,1.5638f,0f,-0.4226f,-0.8028f,1.0923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,-0.0162f,0.0064f,-1.9809f,-0.0032f,0.6306f,-0.2485f,1.6636f,0f,-0.2735f,-0.5734f,0.903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,-0.0074f,0.0026f,-1.0877f,-0.0064f,0.2866f,-0.0994f,0.9657f,0f,-0.1243f,-0.2294f,1.2836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,-0.0074f,0.0026f,-1.5846f,-0.0064f,0.2866f,-0.0994f,0.8382f,0f,-0.1243f,-0.2294f,1.3333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,-0.0088f,0.0026f,-1.7055f,-0.0064f,0.3439f,-0.0994f,0.6783f,0f,-0.1492f,-0.2294f,1.1288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,-0.0074f,0.0026f,-1.5795f,-0.0064f,0.2866f,-0.0994f,0.6394f,0f,-0.1243f,-0.2294f,0.8745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,-0.0103f,0.0064f,-1.2164f,-0.0161f,0.4013f,-0.2485f,1.1096f,0f,-0.174f,-0.5734f,1.1516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,-0.0059f,0.0077f,-1.1275f,-0.0209f,0.2293f,-0.2982f,2.5135f,0f,-0.0994f,-0.6881f,0.6124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,-0.0191f,0.0077f,-1.1334f,-0.0209f,0.7452f,-0.2982f,2.7428f,0f,-0.3232f,-0.6881f,0.5129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,-0.0354f,-0.0089f,-0.2478f,-0.0225f,1.3758f,0.3479f,-0.0883f,0f,0.5966f,-0.8028f,-0.1755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,-0.0354f,0.0089f,1.1164f,-0.0225f,1.3758f,-0.3479f,0.3498f,0f,-0.5966f,-0.8028f,0.9929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000206251,"py":-0.0016055263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args