# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4998f,-0.0217f,0f,-0.0479f,-0.0217f,1.4998f,0f,3.3113f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7499f,-0.0108f,0f,0.712f,-0.0108f,0.7499f,0f,2.6347f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7499f,-0.0108f,0f,-0.0379f,-0.0108f,0.7499f,0f,2.6238f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0624f,-0.0154f,0f,1.0272f,-0.0154f,1.0624f,0f,2.4517f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0624f,-0.0154f,0f,-0.0352f,-0.0154f,1.0624f,0f,2.4363f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7499f,-0.0045f,0f,0.7192f,-0.0108f,0.3125f,0f,2.1347f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7499f,-0.0045f,0f,-0.0307f,-0.0108f,0.3125f,0f,2.1239f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8749f,-0.009f,0f,-0.0217f,-0.0126f,0.6249f,0f,1.4989f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8749f,-0.009f,0f,0.8532f,-0.0126f,0.6249f,0f,1.5116f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8124f,-0.0111f,-0.0035f,1.8398f,-0.0117f,0.7693f,0.2411f,2.4509f,0f,0.2612f,-0.7102f,0.2078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8124f,-0.0034f,-0.0035f,1.8432f,-0.0117f,0.2367f,0.2411f,2.2142f,0f,0.0804f,-0.7102f,0.1275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,-0.0094f,-0.0029f,2.0424f,-0.0018f,0.6509f,0.2009f,1.4085f,0f,0.221f,-0.5918f,-0.213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8749f,-0.0145f,-0.0041f,1.9205f,-0.0126f,1.006f,0.2812f,1.189f,0f,0.3415f,-0.8286f,-0.1549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6249f,-0.006f,-0.0029f,1.8009f,-0.009f,0.4142f,0.2009f,0.8132f,0f,0.1406f,-0.5918f,-0.4139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,-0.0043f,-0.0012f,1.743f,-0.0036f,0.2959f,0.0804f,0.4963f,0f,0.1004f,-0.2367f,-0.4551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,-0.0043f,-0.0012f,1.3038f,-0.0036f,0.2959f,0.0804f,0.6083f,0f,0.1004f,-0.2367f,-0.415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,-0.0051f,-0.0012f,1.8677f,-0.0036f,0.3551f,0.0804f,0.5193f,0f,0.1205f,-0.2367f,-0.712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,-0.0043f,-0.0012f,1.7407f,-0.0036f,0.2959f,0.0804f,0.657f,0f,0.1004f,-0.2367f,-0.9286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8749f,-0.0145f,0.0041f,-1.0841f,-0.0126f,1.006f,-0.2812f,1.4872f,0f,-0.3415f,-0.8286f,0.9735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,-0.0094f,0.0029f,-1.961f,-0.0018f,0.6509f,-0.2009f,1.6119f,0f,-0.221f,-0.5918f,0.7948f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,-0.0043f,0.0012f,-1.0753f,-0.0036f,0.2959f,-0.0804f,0.8753f,0f,-0.1004f,-0.2367f,1.1152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,-0.0043f,0.0012f,-1.5735f,-0.0036f,0.2959f,-0.0804f,0.7497f,0f,-0.1004f,-0.2367f,1.1554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,-0.0051f,0.0012f,-1.6965f,-0.0036f,0.3551f,-0.0804f,0.6084f,0f,-0.1205f,-0.2367f,0.9387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,-0.0043f,0.0012f,-1.5712f,-0.0036f,0.2959f,-0.0804f,0.589f,0f,-0.1004f,-0.2367f,0.6819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6249f,-0.006f,0.0029f,-1.2025f,-0.009f,0.4142f,-0.2009f,1.031f,0f,-0.1406f,-0.5918f,0.9957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8124f,-0.0034f,0.0035f,-1.0984f,-0.0117f,0.2367f,-0.2411f,2.4731f,0f,-0.0804f,-0.7102f,0.5728f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8124f,-0.0111f,0.0035f,-1.1018f,-0.0117f,0.7693f,-0.2411f,2.7098f,0f,-0.2612f,-0.7102f,0.4924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8749f,-0.0205f,-0.0041f,-0.2487f,-0.0126f,1.4202f,0.2812f,-0.0889f,0f,0.4822f,-0.8286f,-0.0511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8749f,-0.0205f,0.0041f,1.1214f,-0.0126f,1.4202f,-0.2812f,0.2557f,0f,-0.4822f,-0.8286f,0.8931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000065262,"py":-0.0009031765,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args