# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.5f,0f,0f,0f,0f,1.5f,0f,3.3125f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.75f,0f,0f,0.75f,0f,0.75f,0f,2.625f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.75f,0f,0f,0f,0f,0.75f,0f,2.625f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0625f,0f,0f,1.0625f,0f,1.0625f,0f,2.4375f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0625f,0f,0f,0f,0f,1.0625f,0f,2.4375f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.75f,0f,0f,0.75f,0f,0.3125f,0f,2.125f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.75f,0f,0f,0f,0f,0.3125f,0f,2.125f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.875f,0f,0f,0f,0f,0.625f,0f,1.5f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.875f,0f,0f,0.875f,0f,0.625f,0f,1.5f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8125f,0f,0f,1.875f,0f,0.8125f,0f,2.5625f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8125f,0f,0f,1.875f,0f,0.25f,0f,2.3125f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0f,0f,2.0625f,0f,0.6875f,0f,1.4375f,0f,0f,-0.625f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.875f,0f,0f,1.9375f,0f,1.0625f,0f,1.25f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.625f,0f,0f,1.8125f,0f,0.4375f,0f,0.8125f,0f,0f,-0.625f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,0f,0f,1.75f,0f,0.3125f,0f,0.5f,0f,0f,-0.25f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,0f,0f,1.3125f,0f,0.3125f,0f,0.625f,0f,0f,-0.25f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,0f,0f,1.875f,0f,0.375f,0f,0.4375f,0f,0f,-0.25f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,0f,0f,1.75f,0f,0.3125f,0f,0.5f,0f,0f,-0.25f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.875f,0f,0f,-1.0625f,0f,1.0625f,0f,1.25f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0f,0f,-1.9375f,0f,0.6875f,0f,1.4375f,0f,0f,-0.625f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,0f,0f,-1.0625f,0f,0.3125f,0f,0.625f,0f,0f,-0.25f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,0f,0f,-1.5625f,0f,0.3125f,0f,0.5f,0f,0f,-0.25f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,0f,0f,-1.6875f,0f,0.375f,0f,0.4375f,0f,0f,-0.25f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,0f,0f,-1.5625f,0f,0.3125f,0f,0.5f,0f,0f,-0.25f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.625f,0f,0f,-1.1875f,0f,0.4375f,0f,0.8125f,0f,0f,-0.625f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8125f,0f,0f,-1.0625f,0f,0.25f,0f,2.3125f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8125f,0f,0f,-1.0625f,0f,0.8125f,0f,2.5625f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.875f,0f,0f,-0.25f,0f,1.5f,0f,0f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.875f,0f,0f,1.125f,0f,1.5f,0f,0f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args