# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4998f,0.0217f,0f,0.0479f,0.0217f,1.4998f,0f,3.3131f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7499f,0.0108f,0f,0.7879f,0.0108f,0.7499f,0f,2.6148f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7499f,0.0108f,0f,0.0379f,0.0108f,0.7499f,0f,2.6256f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0624f,0.0154f,0f,1.0976f,0.0154f,1.0624f,0f,2.4228f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0624f,0.0154f,0f,0.0352f,0.0154f,1.0624f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7499f,0.0045f,0f,0.7806f,0.0108f,0.3125f,0f,2.1148f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7499f,0.0045f,0f,0.0307f,0.0108f,0.3125f,0f,2.1257f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8749f,0.009f,0f,0.0217f,0.0126f,0.6249f,0f,1.5007f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8749f,0.009f,0f,0.8966f,0.0126f,0.6249f,0f,1.4881f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8124f,0.0111f,-0.0035f,1.9145f,0.0117f,0.7693f,-0.2411f,2.72f,0f,-0.2612f,-0.7102f,0.4891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8124f,0.0034f,-0.0035f,1.9111f,0.0117f,0.2367f,-0.2411f,2.4833f,0f,-0.0804f,-0.7102f,0.5695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0094f,-0.0029f,2.0863f,0.0018f,0.6509f,-0.2009f,1.632f,0f,-0.221f,-0.5918f,0.7915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8749f,0.0145f,-0.0041f,1.9593f,0.0126f,1.006f,-0.2812f,1.4964f,0f,-0.3415f,-0.8286f,0.9702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6249f,0.006f,-0.0029f,1.8278f,0.009f,0.4142f,-0.2009f,1.0438f,0f,-0.1406f,-0.5918f,0.9924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,0.0043f,-0.0012f,1.7613f,0.0036f,0.2959f,-0.0804f,0.7689f,0f,-0.1004f,-0.2367f,1.1521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,0.0043f,-0.0012f,1.3255f,0.0036f,0.2959f,-0.0804f,0.8936f,0f,-0.1004f,-0.2367f,1.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,0.0051f,-0.0012f,1.8843f,0.0036f,0.3551f,-0.0804f,0.6276f,0f,-0.1205f,-0.2367f,0.9354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,0.0043f,-0.0012f,1.759f,0.0036f,0.2959f,-0.0804f,0.6082f,0f,-0.1004f,-0.2367f,0.6786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8749f,0.0145f,0.0041f,-1.0453f,0.0126f,1.006f,0.2812f,1.1983f,0f,0.3415f,-0.8286f,-0.1516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0094f,0.0029f,-1.9171f,0.0018f,0.6509f,0.2009f,1.4286f,0f,0.221f,-0.5918f,-0.2097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,0.0043f,0.0012f,-1.0536f,0.0036f,0.2959f,0.0804f,0.6266f,0f,0.1004f,-0.2367f,-0.4116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,0.0043f,0.0012f,-1.5552f,0.0036f,0.2959f,0.0804f,0.5155f,0f,0.1004f,-0.2367f,-0.4518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,0.0051f,0.0012f,-1.6799f,0.0036f,0.3551f,0.0804f,0.5385f,0f,0.1205f,-0.2367f,-0.7086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,0.0043f,0.0012f,-1.5529f,0.0036f,0.2959f,0.0804f,0.6762f,0f,0.1004f,-0.2367f,-0.9253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6249f,0.006f,0.0029f,-1.1757f,0.009f,0.4142f,0.2009f,0.826f,0f,0.1406f,-0.5918f,-0.4106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8124f,0.0034f,0.0035f,-1.0305f,0.0117f,0.2367f,0.2411f,2.2244f,0f,0.0804f,-0.7102f,0.1308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8124f,0.0111f,0.0035f,-1.027f,0.0117f,0.7693f,0.2411f,2.4611f,0f,0.2612f,-0.7102f,0.2112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8749f,0.0205f,-0.0041f,-0.2465f,0.0126f,1.4202f,-0.2812f,0.2415f,0f,-0.4822f,-0.8286f,0.873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8749f,0.0205f,0.0041f,1.1237f,0.0126f,1.4202f,0.2812f,-0.0965f,0f,0.4822f,-0.8286f,-0.0712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000065262,"py":0.0009031765,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args