# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4995f,0.0385f,0f,0.0851f,0.0385f,1.4995f,0f,3.313f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7498f,0.0193f,0f,0.8172f,0.0193f,0.7498f,0f,2.6065f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7498f,0.0193f,0f,0.0675f,0.0193f,0.7498f,0f,2.6257f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,0.0273f,0f,1.1248f,0.0273f,1.0621f,0f,2.411f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,0.0273f,0f,0.0626f,0.0273f,1.0621f,0f,2.4383f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7498f,0.008f,0f,0.8044f,0.0193f,0.3124f,0f,2.1066f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7498f,0.008f,0f,0.0546f,0.0193f,0.3124f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,0.0161f,0f,0.0386f,0.0225f,0.6248f,0f,1.5011f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,0.0161f,0f,0.9133f,0.0225f,0.6248f,0f,1.4786f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,0.0191f,-0.0077f,1.9463f,0.0209f,0.7452f,-0.2982f,2.75f,0f,-0.3232f,-0.6881f,0.5078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,0.0059f,-0.0077f,1.9404f,0.0209f,0.2293f,-0.2982f,2.5207f,0f,-0.0994f,-0.6881f,0.6072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0162f,-0.0064f,2.1065f,0.0032f,0.6306f,-0.2485f,1.6885f,0f,-0.2735f,-0.5734f,0.8979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,0.025f,-0.0089f,1.9784f,0.0225f,0.9745f,-0.3479f,1.5694f,0f,-0.4226f,-0.8028f,1.0872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,0.0103f,-0.0064f,1.8419f,0.0161f,0.4013f,-0.2485f,1.1217f,0f,-0.174f,-0.5734f,1.1465f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,0.0074f,-0.0026f,1.7727f,0.0064f,0.2866f,-0.0994f,0.8615f,0f,-0.1243f,-0.2294f,1.3281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,0.0074f,-0.0026f,1.3383f,0.0064f,0.2866f,-0.0994f,0.9874f,0f,-0.1243f,-0.2294f,1.2784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,0.0088f,-0.0026f,1.8936f,0.0064f,0.3439f,-0.0994f,0.7016f,0f,-0.1492f,-0.2294f,1.1236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,0.0074f,-0.0026f,1.7676f,0.0064f,0.2866f,-0.0994f,0.6627f,0f,-0.1243f,-0.2294f,0.8694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,0.025f,0.0089f,-1.0314f,0.0225f,0.9745f,0.3479f,1.224f,0f,0.4226f,-0.8028f,-0.2998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0162f,0.0064f,-1.9004f,0.0032f,0.6306f,0.2485f,1.4682f,0f,0.2735f,-0.5734f,-0.3399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,0.0074f,0.0026f,-1.0455f,0.0064f,0.2866f,0.0994f,0.6756f,0f,0.1243f,-0.2294f,-0.6057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,0.0074f,0.0026f,-1.5483f,0.0064f,0.2866f,0.0994f,0.5738f,0f,0.1243f,-0.2294f,-0.6555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,0.0088f,0.0026f,-1.6722f,0.0064f,0.3439f,0.0994f,0.6191f,0f,0.1492f,-0.2294f,-0.9097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,0.0074f,0.0026f,-1.5432f,0.0064f,0.2866f,0.0994f,0.7726f,0f,0.1243f,-0.2294f,-1.1142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,0.0103f,0.0064f,-1.1654f,0.0161f,0.4013f,0.2485f,0.8757f,0f,0.174f,-0.5734f,-0.5885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,0.0059f,0.0077f,-1.0057f,0.0209f,0.2293f,0.2982f,2.2234f,0f,0.0994f,-0.6881f,0.0655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,0.0191f,0.0077f,-0.9998f,0.0209f,0.7452f,0.2982f,2.4527f,0f,0.3232f,-0.6881f,0.1649f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,0.0354f,-0.0089f,-0.2417f,0.0225f,1.3758f,-0.3479f,0.3254f,0f,-0.5966f,-0.8028f,0.968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,0.0354f,0.0089f,1.1227f,0.0225f,1.3758f,0.3479f,-0.1024f,0f,0.5966f,-0.8028f,-0.2004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000206251,"py":0.0016055263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args