# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4991f,0.0506f,0f,0.1117f,0.0506f,1.4991f,0f,3.3127f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7496f,0.0253f,0f,0.8381f,0.0253f,0.7496f,0f,2.6003f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7496f,0.0253f,0f,0.0885f,0.0253f,0.7496f,0f,2.6256f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0619f,0.0358f,0f,1.1441f,0.0358f,1.0619f,0f,2.4024f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0619f,0.0358f,0f,0.0822f,0.0358f,1.0619f,0f,2.4382f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7496f,0.0105f,0f,0.8213f,0.0253f,0.3123f,0f,2.1006f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7496f,0.0105f,0f,0.0717f,0.0253f,0.3123f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8745f,0.0211f,0f,0.0506f,0.0295f,0.6246f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8745f,0.0211f,0f,0.9251f,0.0295f,0.6246f,0f,1.4718f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,0.0249f,-0.0105f,1.9687f,0.0274f,0.7383f,-0.3121f,2.7478f,0f,-0.3383f,-0.6819f,0.5118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,0.0077f,-0.0105f,1.9611f,0.0274f,0.2272f,-0.3121f,2.5206f,0f,-0.1041f,-0.6819f,0.6159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.0211f,-0.0088f,2.1208f,0.0042f,0.6247f,-0.2601f,1.6932f,0f,-0.2863f,-0.5682f,0.9234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8745f,0.0326f,-0.0123f,1.9918f,0.0295f,0.9654f,-0.3642f,1.5791f,0f,-0.4425f,-0.7955f,1.1152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,0.0134f,-0.0088f,1.8517f,0.0211f,0.3975f,-0.2601f,1.1337f,0f,-0.1822f,-0.5682f,1.1837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,0.0096f,-0.0035f,1.7806f,0.0084f,0.284f,-0.104f,0.8779f,0f,-0.1301f,-0.2273f,1.3707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,0.0096f,-0.0035f,1.3472f,0.0084f,0.284f,-0.104f,1.0062f,0f,-0.1301f,-0.2273f,1.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,0.0115f,-0.0035f,1.9001f,0.0084f,0.3407f,-0.104f,0.7128f,0f,-0.1562f,-0.2273f,1.1694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,0.0096f,-0.0035f,1.7736f,0.0084f,0.284f,-0.104f,0.6698f,0f,-0.1301f,-0.2273f,0.9161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8745f,0.0326f,0.0123f,-1.0214f,0.0295f,0.9654f,0.3642f,1.238f,0f,0.4425f,-0.7955f,-0.3367f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.0211f,0.0088f,-1.8884f,0.0042f,0.6247f,0.2601f,1.4899f,0f,0.2863f,-0.5682f,-0.3722f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,0.0096f,0.0035f,-1.0397f,0.0084f,0.284f,0.104f,0.6961f,0f,0.1301f,-0.2273f,-0.6538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,0.0096f,0.0035f,-1.5432f,0.0084f,0.284f,0.104f,0.5994f,0f,0.1301f,-0.2273f,-0.7058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,0.0115f,0.0035f,-1.6665f,0.0084f,0.3407f,0.104f,0.6508f,0f,0.1562f,-0.2273f,-0.9591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,0.0096f,0.0035f,-1.5362f,0.0084f,0.284f,0.104f,0.8075f,0f,0.1301f,-0.2273f,-1.1604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,0.0134f,0.0088f,-1.158f,0.0211f,0.3975f,0.2601f,0.8967f,0f,0.1822f,-0.5682f,-0.6325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,0.0077f,0.0105f,-0.9879f,0.0274f,0.2272f,0.3121f,2.2294f,0f,0.1041f,-0.6819f,0.049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,0.0249f,0.0105f,-0.9803f,0.0274f,0.7383f,0.3121f,2.4566f,0f,0.3383f,-0.6819f,0.1531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8745f,0.046f,-0.0123f,-0.2384f,0.0295f,1.363f,-0.3642f,0.3491f,0f,-0.6246f,-0.7955f,0.9907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8745f,0.046f,0.0123f,1.122f,0.0295f,1.363f,0.3642f,-0.1077f,0f,0.6246f,-0.7955f,-0.2326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000355286,"py":0.0021070857,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args