# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4989f,0.0578f,0f,0.1277f,0.0578f,1.4989f,0f,3.3124f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,0.0289f,0f,0.8506f,0.0289f,0.7494f,0f,2.5966f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,0.0289f,0f,0.1012f,0.0289f,0.7494f,0f,2.6255f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,0.0409f,0f,1.1557f,0.0409f,1.0617f,0f,2.3972f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,0.0409f,0f,0.094f,0.0409f,1.0617f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,0.012f,0f,0.8314f,0.0289f,0.3123f,0f,2.0969f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,0.012f,0f,0.0819f,0.0289f,0.3123f,0f,2.1258f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,0.0241f,0f,0.0578f,0.0337f,0.6245f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,0.0241f,0f,0.9322f,0.0337f,0.6245f,0f,1.4676f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,0.0284f,-0.0122f,1.9821f,0.0313f,0.7364f,-0.3156f,2.7418f,0f,-0.3421f,-0.6803f,0.5127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,0.0087f,-0.0122f,1.9733f,0.0313f,0.2266f,-0.3156f,2.5152f,0f,-0.1053f,-0.6803f,0.618f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.024f,-0.0101f,2.1291f,0.0048f,0.6231f,-0.263f,1.6886f,0f,-0.2895f,-0.5669f,0.9298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,0.0371f,-0.0142f,1.9997f,0.0337f,0.963f,-0.3682f,1.5761f,0f,-0.4474f,-0.7936f,1.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,0.0153f,-0.0101f,1.8574f,0.0241f,0.3965f,-0.263f,1.1318f,0f,-0.1842f,-0.5669f,1.1929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.0109f,-0.0041f,1.7851f,0.0096f,0.2832f,-0.1052f,0.8773f,0f,-0.1316f,-0.2268f,1.3812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.0109f,-0.0041f,1.3523f,0.0096f,0.2832f,-0.1052f,1.0074f,0f,-0.1316f,-0.2268f,1.3286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0131f,-0.0041f,1.9037f,0.0096f,0.3399f,-0.1052f,0.7106f,0f,-0.1579f,-0.2268f,1.1808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.0109f,-0.0041f,1.777f,0.0096f,0.2832f,-0.1052f,0.6669f,0f,-0.1316f,-0.2268f,0.9277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,0.0371f,0.0142f,-1.0153f,0.0337f,0.963f,0.3682f,1.2446f,0f,0.4474f,-0.7936f,-0.3459f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.024f,0.0101f,-1.8811f,0.0048f,0.6231f,0.263f,1.5009f,0f,0.2895f,-0.5669f,-0.3803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.0109f,0.0041f,-1.0362f,0.0096f,0.2832f,0.1052f,0.7044f,0f,0.1316f,-0.2268f,-0.6657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.0109f,0.0041f,-1.5402f,0.0096f,0.2832f,0.1052f,0.6104f,0f,0.1316f,-0.2268f,-0.7184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0131f,0.0041f,-1.6632f,0.0096f,0.3399f,0.1052f,0.6638f,0f,0.1579f,-0.2268f,-0.9714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.0109f,0.0041f,-1.5321f,0.0096f,0.2832f,0.1052f,0.8208f,0f,0.1316f,-0.2268f,-1.1719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,0.0153f,0.0101f,-1.1535f,0.0241f,0.3965f,0.263f,0.9055f,0f,0.1842f,-0.5669f,-0.6435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,0.0087f,0.0122f,-0.9772f,0.0313f,0.2266f,0.3156f,2.2339f,0f,0.1053f,-0.6803f,0.0448f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,0.0284f,0.0122f,-0.9685f,0.0313f,0.7364f,0.3156f,2.4605f,0f,0.3421f,-0.6803f,0.1501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,0.0524f,-0.0142f,-0.2365f,0.0337f,1.3595f,-0.3682f,0.356f,0f,-0.6316f,-0.7936f,0.9963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,0.0524f,0.0142f,1.1215f,0.0337f,1.3595f,0.3682f,-0.112f,0f,0.6316f,-0.7936f,-0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000464033,"py":0.0024079583,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args