# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage rd_models:blackstone_golem rig_hash set value '427c4734e835dcc6149551a808277e14aa864a82250c2829ed55d6282969f8d0'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.stomp.frame dummy