# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute at @n[tag=RD.blackstone_golem,type=creeper,distance=..2] rotated ~ 0 run tp @s ~ ~ ~ ~ ~
execute as @n[tag=RD.blackstone_golem,type=creeper,distance=..0.5] at @s run function custom_ai:custom_mobs/animated_java/blackstone_golem/tick
execute if entity @s[tag=RD.initialized] unless entity @n[type=minecraft:creeper,tag=RD.blackstone_golem] as @n[tag=rd_models.blackstone_golem.root] run function rd_models:blackstone_golem/remove/this