# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function rd_models:blackstone_golem/zzz/reset_floating_entities
function rd_models:blackstone_golem/zzz/set_default_pose_to_nodes with storage animated_java:temp entry.data.uuids_by_name