# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "rd_models:blackstone_golem"
data modify storage animated_java:temp entry.data.rig_hash set value "427c4734e835dcc6149551a808277e14aa864a82250c2829ed55d6282969f8d0"
tp @s ~ ~ ~ ~ ~
summon minecraft:marker ^0 ^0 ^0 {Tags:["RD.blackstone_golem","aj.global.bone.bs_golem_bone.child","aj.global.bone.bs_golem_bone.child.locator","aj.global.bone.bs_golem_bone.decendant","aj.global.bone.bs_golem_bone.decendant.locator","aj.global.bone.bs_golem_bone.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator","aj.new","rd_models.blackstone_golem.bone.bs_golem_bone.child","rd_models.blackstone_golem.bone.bs_golem_bone.child.locator","rd_models.blackstone_golem.bone.bs_golem_bone.decendant","rd_models.blackstone_golem.bone.bs_golem_bone.decendant.locator","rd_models.blackstone_golem.bone.bs_golem_bone.tree","rd_models.blackstone_golem.entity","rd_models.blackstone_golem.locator","rd_models.blackstone_golem.locator.locator","rd_models.blackstone_golem.node","rd_models.blackstone_golem.node.locator"]}
execute as @n[ type=minecraft:marker, tag=rd_models.blackstone_golem.locator.locator, tag=aj.new, distance=..1 ] run function rd_models:blackstone_golem/zzz/summon/as_locator/locator
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.locator set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.locator.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.item_display] run function rd_models:blackstone_golem/zzz/summon/as_node/item_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.item_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display1] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display2] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display3] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display4] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display10] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display8] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display24] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display24
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display24 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display23] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display23
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display23 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display5] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display25] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display25
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display25 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display7] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display6] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display9] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display11] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display11
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display11 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display14] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display12] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display13] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display16] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display16
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display16 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display18] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display18
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display18 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display20] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display20
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display20 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display19] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display19
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display19 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display21] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display21
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display21 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display22] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display22
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display22 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display17] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display17
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display17 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display26] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display26
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display26 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display15] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display15
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display15 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display27] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display27
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display27 set from storage animated_java:gu out
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.block_display28] run function rd_models:blackstone_golem/zzz/summon/as_node/block_display28
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display28 set from storage animated_java:gu out
function rd_models:blackstone_golem/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.locator
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function rd_models:blackstone_golem/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function rd_models:blackstone_golem/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function rd_models:blackstone_golem/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function rd_models:blackstone_golem/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function rd_models:blackstone_golem/zzz/summon/zzz/1 with storage animated_java:temp entry.data.locators.locator
execute on passengers if entity @s[tag=rd_models.blackstone_golem.node.item_display] run function rd_models:blackstone_golem/zzz/summon/on_summon/item_display_item_display
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount