# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage rd_models:test_cube rig_hash set value '46a8bb8459f5812dcdbc118c225240e231ddb4912eddcaf255b2c1ae8a18a247'
scoreboard objectives add aj.spin.frame dummy