# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(item_display) ~ ~ ~ ~ ~
$execute as $(item_display) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display1) ~ ~ ~ ~ ~
$execute as $(block_display1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display2) ~ ~ ~ ~ ~
$execute as $(block_display2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display3) ~ ~ ~ ~ ~
$execute as $(block_display3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display4) ~ ~ ~ ~ ~
$execute as $(block_display4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display10) ~ ~ ~ ~ ~
$execute as $(block_display10) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display8) ~ ~ ~ ~ ~
$execute as $(block_display8) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display24) ~ ~ ~ ~ ~
$execute as $(block_display24) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display23) ~ ~ ~ ~ ~
$execute as $(block_display23) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display5) ~ ~ ~ ~ ~
$execute as $(block_display5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display25) ~ ~ ~ ~ ~
$execute as $(block_display25) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display7) ~ ~ ~ ~ ~
$execute as $(block_display7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display6) ~ ~ ~ ~ ~
$execute as $(block_display6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display9) ~ ~ ~ ~ ~
$execute as $(block_display9) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display11) ~ ~ ~ ~ ~
$execute as $(block_display11) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display14) ~ ~ ~ ~ ~
$execute as $(block_display14) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display12) ~ ~ ~ ~ ~
$execute as $(block_display12) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display13) ~ ~ ~ ~ ~
$execute as $(block_display13) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display16) ~ ~ ~ ~ ~
$execute as $(block_display16) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display18) ~ ~ ~ ~ ~
$execute as $(block_display18) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display20) ~ ~ ~ ~ ~
$execute as $(block_display20) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display19) ~ ~ ~ ~ ~
$execute as $(block_display19) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display21) ~ ~ ~ ~ ~
$execute as $(block_display21) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display22) ~ ~ ~ ~ ~
$execute as $(block_display22) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display17) ~ ~ ~ ~ ~
$execute as $(block_display17) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display26) ~ ~ ~ ~ ~
$execute as $(block_display26) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display15) ~ ~ ~ ~ ~
$execute as $(block_display15) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display27) ~ ~ ~ ~ ~
$execute as $(block_display27) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(block_display28) ~ ~ ~ ~ ~
$execute as $(block_display28) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1