# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=rd_models.blackstone_golem.animation.idle.playing] run function rd_models:blackstone_golem/animations/idle/zzz/on_tick
execute if entity @s[tag=rd_models.blackstone_golem.animation.walk.playing] run function rd_models:blackstone_golem/animations/walk/zzz/on_tick
execute if entity @s[tag=rd_models.blackstone_golem.animation.stomp.playing] run function rd_models:blackstone_golem/animations/stomp/zzz/on_tick
function rd_models:blackstone_golem/root/on_tick/transform_floating_entities
function rd_models:blackstone_golem/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
execute at @n[tag=RD.blackstone_golem,type=marker] run tp @s ~ ~ ~ ~ ~