# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function rd_models:_internal/creeper_internal {"args":[{"id":"scale",base:2f},{"id":"max_health",base:200f},{"id":"armor",base:8f},{id:"movement_speed",base:0.25f}],"id":"RD.blackstone_golem","name":{"text":"ブラックストーンゴーレム"}}
effect give @s resistance infinite 255