# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.stomp.frame 0
tag @s add aj.transforms_only
execute at @s run function rd_models:blackstone_golem/animations/stomp/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove rd_models.blackstone_golem.animation.stomp.playing