# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 run function rd_models:blackstone_golem/animations/stomp/zzz/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.stomp.frame
function rd_models:blackstone_golem/animations/stomp/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.stomp.frame matches 1 run return run function rd_models:blackstone_golem/animations/stomp/zzz/loop_mode_stop
scoreboard players add @s aj.stomp.frame 1